### ISSUE TITLE
建议更新为调用GPT3.5接口，费用更便宜、回答速度更快，答案也能智能。

### ISSUE THREAD

**Issue by hhun** [lblblong/mossgpt-utools#1]

**Comment by hhun** [comment]
聊天输入框里面的字体建议改成微软雅黑，宋体看着难受。

**Comment by lblblong** [comment]
好的，有时间改一下

**Comment by lblblong** [comment]
已经添加 3.5-turbo 的支持提交插件市场审核了，也可以下载我打的包提前使用：https://github.com/lblblong/mossgpt-utools/releases/tag/v1.3.0

**Comment by hhun** [comment]
> 已经添加 3.5-turbo 的支持提交插件市场审核了，也可以下载我打的包提前使用：https://github.com/lblblong/mossgpt-utools/releases/tag/v1.3.0

幸苦了！
