### ISSUE TITLE
支持复制代码块内容的按钮

### ISSUE THREAD

**Issue by mkdir700** [lblblong/mossgpt-utools#18]

**Comment by lblblong** [comment]
已添加
https://github.com/lblblong/mossgpt-utools/releases/tag/v1.4.0

**Comment by mkdir700** [comment]
问下，utools 插件市场什么时候可以更新

**Comment by lblblong** [comment]
utools官方审核比较慢，我感觉至少得下周了，上次周五提交审核好像是下周二才审核通过
