### ISSUE TITLE
在 gpt 回复过程中打断滚动至底部的效果

### ISSUE THREAD

**Issue by mkdir700** [lblblong/mossgpt-utools#24]
在 gpt 正在回复时，我们向上翻阅将会强制滚动至底部。

是否可以修改逻辑为，向上滚动的逻辑优先级最高，即便此时 gpt 正在输出内容。

**Comment by lblblong** [comment]
已处理：https://github.com/lblblong/mossgpt-utools/releases/tag/v1.6.0

**Comment by mkdir700** [comment]
> 已处理：https://github.com/lblblong/mossgpt-utools/releases/tag/v1.6.0

这个问题貌似还是存在，在回复过程中无法浏览历史对象，会被强制居底

**Comment by lblblong** [comment]
> > 已处理：https://github.com/lblblong/mossgpt-utools/releases/tag/v1.6.0
> 
> 这个问题貌似还是存在，在回复过程中无法浏览历史对象，会被强制居底

现在这里处理的还不太完美，不过能解决一部分问题，有时间再优化下😂
