### ISSUE TITLE
Moss和OpenAI的ChatGPT的关系？

### ISSUE THREAD

**Issue by m3lab-zzl** [lblblong/mossgpt-utools#26]
问了Moss，回答说是两个东西，没有什么关系，也没调用ChatGPT的什么接口。

那为什么使用之前需要提供OpenAI的API_KEY？

**Comment by lblblong** [comment]
emmm，怎么说呢，chatgpt 是 openai 开放给 c 端用户的最终产品，openai 提供的 api 是给 b 端用户定制自己的 ai 产品的。
可以说 chatgpt 是 openai 基于自己的 api 搭建的一个 c 端产品，我们这个就相当于基于 openai 的 api 搭建了其他的产品，和 chatgpt 或许使用了相同的模型，但却不一样。
并且 ai 的身份是由 prompt 指定的，你完全可以在设置界面修改 prompt 让它是 chatgpt

**Comment by m3lab-zzl** [comment]
多谢答疑。都是调用openai的API，所以Moss和ChatGPT是同级产品，内核都是openai的东西。

那它们分析回答问题的逻辑有什么不同么，还是说只是外壳不一样？

**Comment by lblblong** [comment]
chatgpt 的 prompt 是官方调教的，而且模型也做了一些优化，所以回复的内容可能会更好一些，另外 chatgpt 所用的模型限制更多一些，因为是直接面向c端的，所以它总是会说自己只是一个AI，不具备感情之类的
