### ISSUE TITLE
新建会话黑屏

### ISSUE THREAD

**Issue by mkdir700** [lblblong/mossgpt-utools#32]
![](https://cdn.z2blog.com/utools/pic/Mar-13-2023%2022-26-18.gif)

调试信息
<img width="836" alt="image" src="https://user-images.githubusercontent.com/56359329/224730543-41bc76aa-8865-4c9b-a5a6-a27191205609.png">

**Comment by lblblong** [comment]
拉最新的代码

**Comment by mkdir700** [comment]
> 拉最新的代码

嗯，可以了
