### ISSUE TITLE
停止回复按钮

### ISSUE THREAD

**Issue by mkdir700** [lblblong/mossgpt-utools#36]
在 gpt 返回生成响应的过程中，可以点击停止按钮，提前结束回复。

**Comment by mkdir700** [comment]
https://github.com/Chanzhaoyu/chatgpt-web 这个项目可以抄，啊不是，借鉴下

**Comment by lblblong** [comment]
已添加：https://github.com/lblblong/mossgpt-utools/releases/tag/v1.11.0
