### ISSUE TITLE
可以调整发送按键吗？

### ISSUE THREAD

**Issue by Keryyyy** [lblblong/mossgpt-utools#38]
现在默认Enter键是发送，但是有些情况需要用Enter作为换行
希望加入Ctrl+Enter发送的选项

**Comment by lblblong** [comment]
可以 shift + enter 换行

**Comment by mkdir700** [comment]
> 可以 shift + enter 换行

可以考虑在设置中增加一向，发送快捷键的设置，类似于微信。

每个人的使用习惯不一样。

**Comment by lblblong** [comment]
已支持
https://github.com/lblblong/mossgpt-utools/releases/tag/v1.11.12
![image](https://user-images.githubusercontent.com/18625523/228277175-febf87f0-af0f-44f7-b89d-0ad7534bbfd8.png)

**Comment by jluncc** [comment]
macOS 一般是 command 键替代 control 键，例如是 command + c/v 为复制粘贴。  

可以支持 ctrl 在 macOS 里替换为 command 键吗？
