### ISSUE TITLE
是否可以替换api base

### ISSUE THREAD

**Issue by lgjssn** [lblblong/mossgpt-utools#39]
想要把请求的 https://**api.openai.com/**v1/chat/completions 替换为自己的域名，目前的被墙了。  
可否开放修改，或者请求告知一下怎么去改code。  
非常感谢！我在terminal上可以用改后的域名正常访问了，但是utools上还是一直提示被墙。

**Comment by mkdir700** [comment]
下个版本加上

**Comment by lblblong** [comment]
是在自己的服务器做了反向代理吗

**Comment by lblblong** [comment]
做反向代理不如直接通过代理转发请求，可以在设置里设置代理的
![image](https://user-images.githubusercontent.com/18625523/225919283-a0621ec4-9be9-4769-a62d-68f4f8af6aa1.png)

**Comment by lgjssn** [comment]
> 做反向代理不如直接通过代理转发请求，可以在设置里设置代理的 ![image](https://user-images.githubusercontent.com/18625523/225919283-a0621ec4-9be9-4769-a62d-68f4f8af6aa1.png)

感谢建议！这里我是新手不太会使用，base url是朋友搭好了分享给我的，我在terminal上使用正常所以想迁移到utools上。
有比较方便的搭建api代理的方法？我也可以学习搭建一下

**Comment by lgjssn** [comment]
> > 
> 
> 如果是 linux 的话可以通过 tinyproxy 搭建，很方便的，如果是 windows 可以用 wproxy，图形界面很简单
> 
> 也有免费的代理网站：https://checkerproxy.net/archive/2023-03-17

感谢，我会研究研究。希望修改api_base的功能也早日上线~

**Comment by lblblong** [comment]
已支持

**Comment by lgjssn** [comment]
我又来了，更换了自己的api base之后，终于可以连上了，但是看起来无论我说什么，它都在自我介绍，似乎我的对话文本没有传递过去。开新会话，或者使用已有的模板也一样。
![image](https://user-images.githubusercontent.com/30599505/226186500-c1344ee8-18f3-4cd3-b796-421057ef64f1.png)

**Comment by lgjssn** [comment]
另外，建议提示文本里面，加上v1,例如
https://apiproxy.myopenai.com/v1
没有v1的话会报错
