### ISSUE TITLE
免费的 ChatGPT 网站收集

### ISSUE THREAD

**Issue by lblblong** [lblblong/mossgpt-utools#4]
大家有一些免费的 ChatGPT 的网站可以在这里分享哈！！！

有失效的也可以在评论区留言回复一下~

### 2023 年 3 月 18 更新
1. https://chat.theb.ai 
2. https://www.aitoolgpt.com 
3. https://chatforai.com
4. https://freechatgpt.chat 
5. https://fastgpt.app
6. https://ai.ls
7. https://chatgpt.ddiu.me
8. https://freegpt.one
9. https://freegpt.cc
10. https://www.mulaen.com
11. https://chat.tgbot.co/chat
12. https://fastgpt.app
13. https://chat.yqcloud.top
14. https://ai117.com/
15. https://zhoubaotong.com/zh
16. https://gpt.sheepig.top/chat
17. https://chat.forchange.cn
18. https://gpt.tool00.com
19. https://openaizh.com/chatgpt.html
20. https://chat.gptocean.com
21. https://hi.icu
22. https://aicodehelper.com
23. https://ai.zecoba.cn
24. https://ai-toolbox.codefuture.top
25. https://gptzero.me
26. https://chat35.com/chat
27. https://94gpt.com
28. https://chat.forchange.cn
29. https://aigcfun.com
30. https://askai.ws
31. https://chat.moyunav.com
32. https://chatforai.com
33. https://gpt.tool00.com
34. https://fastgpt.app
35. https://chater.lanyun1103.top
36. https://chat.javaex.cn

----

1. https://fastgpt.app/
2. https://chat.binjie.site:7777/#/chat
3. https://ai.ls/
37. https://aitools.run/  （AI帮个忙，多功能 AI 小助手）
38. https://future.attejuvonen.fi/
39. https://freechatgpt.chat/
40. https://94gpt.com/
41. https://chat.tgbot.co/

**Comment by chengwb53** [comment]
mark

**Comment by dashi6174** [comment]
好人呀

**Comment by chengxumeng** [comment]
谢谢

**Comment by quiet-go** [comment]
感谢~

**Comment by clayboby** [comment]
补一个我知道带GPT4的，https://www.vivi-chat.com/#/chat。挺快挺好用

**Comment by zhk0603** [comment]
补充： https://52aicopilot.cc (Ai Copilot 全能AI助手）

**Comment by yuguiyyg** [comment]
https://chat.zhenbs.com/#/invitation?referralCode=CY62S91F

**Comment by tree-free** [comment]
mark

**Comment by BH-0** [comment]
这个速度蛮快的：https://chat35.com/i/niOtvv

**Comment by BH-0** [comment]
> 这个速度蛮快的：https://gpt.ai-copilot.cn/#/?invited=e9487e6f15a211ee99560242ac120003

**Comment by xuxiansheng2018** [comment]
mark

**Comment by SailFan** [comment]
好人啊
