### ISSUE TITLE
发送消息失败 Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by mkdir700** [lblblong/mossgpt-utools#42]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/56359329/226079269-8a79874f-f260-4e40-b71c-f3df5bf0645b.png">

**Comment by mkdir700** [comment]
出现的原因，可能是 user 发送的消息丢失了，为什么会丢失暂时不清楚。

解决方法：新开一个会话。

**Comment by lblblong** [comment]
有在这个会话删除过消息吗

**Comment by mkdir700** [comment]
> Owner
没有，#7 更新这个之后，打开问题会话，用户发的消息不见了。然后就出现这个问题了

**Comment by mkdir700** [comment]
> 有在这个会话删除过消息吗

没有，#7 更新这个之后，打开问题会话，用户发的第一条消息不见了，然后就出现这个问题了
