### ISSUE TITLE
翻译的对话框体验不是很好

### ISSUE THREAD

**Issue by dashi6174** [lblblong/mossgpt-utools#46]
稍微动一下，就开始翻译了，消耗token，感觉自己没法控制

**Comment by lblblong** [comment]
好的，之后会提供一个选项关闭自动触发翻译

**Comment by lblblong** [comment]
已经支持了，插件市场的也可以，或者下载最新的：
https://github.com/lblblong/mossgpt-utools/releases/tag/v1.11.12
