### ISSUE TITLE
使用自定义的API接口404错误

### ISSUE THREAD

**Issue by sosel** [lblblong/mossgpt-utools#50]
ChatGPT error 404: { "error": { "message": "Invalid URL (POST /chat/completions)", "type": "invalid_request_error", "param": null, "code": null } }
对话框回复这个错误

**Comment by lblblong** [comment]
你可以尝试用这个部署试试：https://github.com/justjavac/openai-proxy

**Comment by lblblong** [comment]
直接使用也可以：https://closeai.deno.dev/v1

**Comment by sosel** [comment]
感谢回复，已解决，我也在自己的接口上加上/v1 就可以了。谢谢
