### ISSUE TITLE
2.0版本更新后无法启动，MossGPT-2.0.0.upx插件拖动到utools输入后无法启动

### ISSUE THREAD

**Issue by lmdheart** [lblblong/mossgpt-utools#55]
![本地启动提示](https://user-images.githubusercontent.com/17795428/230302022-f7047e04-63bc-48ef-8259-7069816b3dd7.jpg)

**Comment by lblblong** [comment]
搞错啦，不是作为文件启动，而是作为插件安装。

你先用 ctrl + c 复制它，然后再呼出 utools，应该就可以看到插件安装选项了 
![image](https://user-images.githubusercontent.com/18625523/230302739-38687691-7699-483d-b7d9-1eba25c18443.png)
