### ISSUE TITLE
代码块不能左右移动

### ISSUE THREAD

**Issue by jluncc** [lblblong/mossgpt-utools#6]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/18534759/223916861-6e027c83-0cb3-4b54-a536-304f347718bc.png">

回答显示的代码块，不能左右移动

**Comment by hhun** [comment]
代码块要弄成自动换行

**Comment by mkdir700** [comment]
@lblblong 单行内容过长会有这个问题，如图：

promt 复现：
```
以 Markdown 形式展示这张图 https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Kitten_in_Rizal_Park%2C_Manila.jpg/640px-Kitten_in_Rizal_Park%2C_Manila.jpg
```

<img width="836" alt="image" src="https://user-images.githubusercontent.com/56359329/223987288-fde1f4f3-ebf3-4cc9-ae1b-bcbee283e825.png">
