### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by person2217** [lblblong/mossgpt-utools#67]
国外使用mossgpt，network error一直弹窗
![image](https://github.com/user-attachments/assets/07acfaec-e4e0-4a8e-a838-7f4904a8eef2)

**Comment by lblblong** [comment]
挂国内的代理试试呢

**Comment by lblblong** [comment]
moss的服务是部署在腾讯云的，不确定是不是限制了访问

**Comment by person2217** [comment]
好的，事实上没有回国代理。不过最近好了。
