### ISSUE TITLE
建议增加：复制、删除 单条内容

### ISSUE THREAD

**Issue by hhun** [lblblong/mossgpt-utools#7]

**Comment by mkdir700** [comment]
@lblblong 复制 gpt 回复内容，有什么好的想法和实现吗

**Comment by mkdir700** [comment]
我的想法是回复 box 内支持右键点击，点击之后可以选择删除或复制整个回复内容。

**Comment by hhun** [comment]
双击复制内容，右键菜单可以选择删除。

**Comment by mkdir700** [comment]
> 双击复制内容，右键菜单可以选择删除。

双击也可能是选中单行

**Comment by lblblong** [comment]
> 我的想法是回复 box 内支持右键点击，点击之后可以选择删除或复制整个回复内容。

这种交互没有问题，复制也很好实现

删除单条消息需要调整一下代码的逻辑，现在是确保消息成对匹配的

**Comment by mkdir700** [comment]
> > 我的想法是回复 box 内支持右键点击，点击之后可以选择删除或复制整个回复内容。
> 
> 这种交互没有问题，复制也很好实现
> 
> 删除单条消息需要调整一下代码的逻辑，现在是确保消息成对匹配的

删除消息需要修改数据模型，发送/接收两条消息需要相互绑定，这样才能在删除一条消息的同时删除另一条。

需要新增一个字段吗，比如 linkMessageId，表示与之绑定的另一条消息的 Id

**Comment by lblblong** [comment]
> > > 我的想法是回复 box 内支持右键点击，点击之后可以选择删除或复制整个回复内容。
> > 
> > 这种交互没有问题，复制也很好实现
> > 
> > 删除单条消息需要调整一下代码的逻辑，现在是确保消息成对匹配的
> 
> 删除消息需要修改数据模型，发送/接收两条消息需要相互绑定，这样才能在删除一条消息的同时删除另一条。
> 
> 需要新增一个字段吗，比如 linkMessageId，表示与之绑定的另一条消息的 Id

不用，通过parentMessageId已经是可以找到对应的问句消息或者答句消息的

这里我在想要不要去掉这个成对匹配的机制，当时是为了方便实现消息重试的功能才强制要求一问一答的，实际上是可以不用非要一问一答的，这里我再想想

**Comment by mkdir700** [comment]
@lblblong 这个目前有什么好的想法吗

**Comment by lblblong** [comment]
> @lblblong 这个目前有什么好的想法吗

我晚上整一下下子

**Comment by lblblong** [comment]
已支持复制、删除：https://github.com/lblblong/mossgpt-utools/releases/tag/v1.8.0
